services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST_IP=api-gateway
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    env_file:
      - .env
    depends_on:
      - consul

  authentication:
    build: ./authentication
    ports:
      - "4000:4000"
    environment:
      - HOST_IP=authentication
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD} 
      - REDIS_URL=${REDIS_URL}
      - REDIS_PORT=${REDIS_PORT}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}  
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - redis
      - consul
      - postgres
  
  auctions:
    build: ./auctions
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - CONSUL_HOST=${CONSUL_HOST}
      - CONSUL_PORT=${CONSUL_PORT}
    depends_on:
      - consul
      - mongo
      - authentication

  payments:
    build: ./payments
    ports:
      - "4001:4001"
    environment:
      - HOST_IP=payments
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - MERCADOPAGO_ACCESS_TOKEN=${MERCADOPAGO_ACCESS_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD} 
      - REDIS_URL=${REDIS_URL}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - consul
      - redis
      - postgres

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3002:3000"
    depends_on:
      - prometheus

  consul:
    image: consul:1.15
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"

  redis:
    image: "redis:latest"
    container_name: redis-container
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  postgres:
    image: "postgres:latest"
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    
  mongo:
    image: "mongo:latest"
    container_name: mongo-container
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  postgres-data:
  mongo-data:
  redis-data:
