global:
  scrape_interval: 15s
scrape_configs:
  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:3000"]
  - job_name: "authentication"
    static_configs:
      - targets: ["authentication:4000"]
