global:
  scrape_interval: 15s
scrape_configs:
  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:3000"]
  - job_name: "example-microservice"
    static_configs:
      - targets: ["example-microservice:3001"]
